# Cleaner Desktop  

<!--
**Urgent Notice:** | Urgent or important info should be put here
:---:|--- 
-->

&nbsp;

> "This repository is a workspace of the Cleaner Desktop GUI.  
Files seen on the Master branch are the intended release version.  
We are not responsible for damages or performance issues from the use of unreleased builds.
This project is intended for non commercial use and may not be compatible on all systems.
Please use at your own discretion."

&nbsp;

#### What is Cleaner Desktop?

Cleaner Desktop is a [Rainmeter](https://www.rainmeter.net/ "Rainmeter, desktop customization tool")
skin intended for users who enjoy less clutter. Our skin takes advantage of the empty space on your
desktop to create a summonable menu that is quick and easy to use.  
&nbsp;

#### The Final Mission

Our desktop customization skin will provide a easy, clean, and stylish menu to access directories while giving a crystal clear desktop background.  
&nbsp;

#### The Spark

At the time of the creation of this project, the founders were computing students that discovered their gradually messier and messier
desktops. With the increasing workload, more and more projects and assignments were carelessly laid onto the desktop and
inhibited the view of their desktop backgrounds. They liked the idea of open source resources and decided to make an easy and elegant
user interface which has access to files and shortcuts all the same.  
&nbsp;

<!--//////////////////////////////////////////////////////////////////////////////////////
                                   TABLE OF CONTENTS
//////////////////////////////////////////////////////////////////////////////////////////-->


## Table of contents
&nbsp;  
[Changelog](#change-log)  
[In Development](#in-development)  
[Known Issues](#known-issues)  
[Patch Notes](#patch-notes)  
Previous Patches - not available at this time :sob:  
[Version notes](#version)  
&nbsp;

___


<!--//////////////////////////////////////////////////////////////////////////////////////
                                     CHANGE LOG
//////////////////////////////////////////////////////////////////////////////////////////-->


### Change log
Major changes will be added here. If a new feature is added or an old one is gone, this is the first place to look. :wink:  
\[v**0.0**.000]
```diff
Summary: Nothing has happened yet
```
&nbsp;

&nbsp;

&nbsp;
<!--    Placeholders  -->
&nbsp;

&nbsp;

[back to top](#cleaner-desktop) | [table of contents](#table-of-contents)
---|---
___


<!--//////////////////////////////////////////////////////////////////////////////////////
                                    IN DEVELOPMENT
//////////////////////////////////////////////////////////////////////////////////////////-->


### In Development
Features that we have confirmed and are in development but are not ready to be released ***may*** be posted here.  
There is no obligation to update this section, but we do like the hype.
- currently: EVERYTHING 

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

[back to top](#cleaner-desktop) | [table of contents](#table-of-contents)
---|---
___


<!--//////////////////////////////////////////////////////////////////////////////////////
                                     KNOWN ISSUES
//////////////////////////////////////////////////////////////////////////////////////////-->


### Known Issues
This list will be updated periodically based on bugs that we have found or have received notice about and have not gotten around to fixing
or do not know how to fix at the given time.  
- nothing to show here at this moment.
- There is no download yet; we are aware of this fact.
- There is almost nothing here yet; we are also aware of this fact.

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

[back to top](#cleaner-desktop) | [table of contents](#table-of-contents)
---|---
___


<!--//////////////////////////////////////////////////////////////////////////////////////
                                     PATCH NOTES
//////////////////////////////////////////////////////////////////////////////////////////-->



### Patch Notes \(June 5, 2017)
bug updates and minor adjustments will be posted here.  
\[v0.0.**000**]  
- nothing to show here at this moment

Previous Patches - not available at this time :sob: <!-- link update log branch here -->

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

[back to top](#cleaner-desktop) | [table of contents](#table-of-contents)
---|---
___


<!--//////////////////////////////////////////////////////////////////////////////////////
                                        VERSION
//////////////////////////////////////////////////////////////////////////////////////////-->


### Version
Version updates are release for the project based on the most recent stable build. We will be separating our updates into 3 digit categories as per semantic version naming conventions i.e. **MAJOR**.**MINOR**.**PATCH**.  
For the purpose of clarifying our version number, we will denote it starting with a "v".

**\[v0.0.000]**  
Nothing here yet; waiting for the first version to be born :eyes:

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

[back to top](#cleaner-desktop) | [table of contents](#table-of-contents)
---|---
